version: '3'
services:
  consul:
    image: consul:1.4.2
    container_name: shopmi-consul
    restart: always
    volumes:
    - shopmi-consul-data:/consul/data
    network_mode: "host"
    command: "agent -server -ui -bootstrap-expect=1 -client=127.0.0.1 -bind=127.0.0.1 -data-dir /consul/data"
  mysql:
    image: mysql:8.0.13
    container_name: shopmi-mysql
    restart: always
    environment:
    - MYSQL_DATABASE=users
    - MYSQL_ROOT_PASSWORD=2cb59d0bcd6a4a96aaf52e368aeacde7 # TODO SHOULD BE SECRET IN THE FUTURE
    - MYSQL_HOST=127.0.0.1
    - MYSQL_PORT=3306
    volumes:
    - shopmi-mysql-data:/var/lib/mysql
    - ./database/users.sql:/docker-entrypoint-initdb.d/users.sql
    network_mode: "host"
volumes:
  shopmi-consul-data:
  shopmi-mysql-data: