ALTER DATABASE mydb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE USERS (
    NAME VARCHAR(255),
    SURNAME VARCHAR(255),
    PESEL VARCHAR(12),
    DATE_OF_BIRTH DATE,
    ZIP_CODE VARCHAR(7),
    CITY VARCHAR(255),
    STREET VARCHAR(255),
    HOUSE_NUMBER VARCHAR(255)
);