ALTER DATABASE users CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE USERS(
    ID INTEGER AUTO_INCREMENT,
    FIRST_NAME VARCHAR(41),
    LAST_NAME VARCHAR(41),
    USERNAME VARCHAR(21),
    PASSWORD BINARY(16), -- AES 256 gives 16 byte password
    SALT BINARY(16), -- AES 256 gives 16 byte salt
    EMAIL VARCHAR(41),
    PHONE_NUMBER VARCHAR(25),
    COUNTRY_CODE CHAR(3),
    PRIMARY KEY (ID)
);

ALTER TABLE USERS AUTO_INCREMENT=10001;